- name: install/update packages
  apt:
    name:
      - build-essential
      - autoconf
      - libtool
      - libpcap-dev
      - pkg-config
      - git
    state: latest
- file: path=/dpmi state=directory

# libcap_utils
- name: update libcap_utils repo
  register: libcap_utils_repo
  git:
    dest: /dpmi/libcap_utils
    repo: https://github.com/DPMI/libcap_utils.git
- name: rebuild libcap_utils
  script: rebuild.sh /dpmi/libcap_utils
  when: libcap_utils_repo|changed
